### ISSUE TITLE
Constrained delegation/AllowedToDelegate edges not identified

### ISSUE THREAD

**Issue by jsdhasfedssad** [dirkjanm/BloodHound.py#127]
Hi,

I have been testing constrained delegation abuse and noted that if I dump the AD using Sharphound.exe I can see a expected edge, AllowedToDelegate,  between a user object and a computer object. However, if I dump the AD using bloodhound.py with the flags "all,LoggedOn" enabled this edge is missing.

**Comment by deadbeefmonster** [comment]
I experienced the same with -c All 

`bloodhound_1  | {"level":"error","time":"2023-08-29T13:39:15.466909926Z","message":"Error processing ingest task 19: json: cannot unmarshal string into Go struct field User.AllowedToDelegate of type ein.TypedPrincipal"}`
`bloodhound_1  | {"level":"error","time":"2023-08-29T13:49:52.174938378Z","message":"Error processing ingest task 9: json: cannot unmarshal string into Go struct field Computer.AllowedToDelegate of type ein.TypedPrincipal"}`
