### ISSUE TITLE
Domain Trust data is no longer importing - Bloodhound 4.3.1

### ISSUE THREAD

**Issue by 0x48756773** [dirkjanm/BloodHound.py#136]
Domain trust information is no longer being imported as Bloodhound 4.3.1 has switched back to using integers to represent Trust Types and Trust Direction.

Change was made in this commit - https://github.com/BloodHoundAD/BloodHound/commit/7d3c0fb02cee29f62f18ceb3f9460ce51c8b4a0e

Suggest rolling back the changes in commit -
https://github.com/fox-it/BloodHound.py/commit/273984883d9ca3dd21f6fca35ec88671cac3fc87

**Comment by dirkjanm** [comment]
thanks for noticing, I've moved the logic back to the old behaviour
