### ISSUE TITLE
ModuleNotFoundError - Running bloodhound-python script

### ISSUE THREAD

**Issue by RunRenegade** [dirkjanm/BloodHound.py#163]
Hi, 

Hoping for some help, getting a `ModuleNotFoundError: No module named 'bloodhound'` when running the `bloodhound-python` script.

Originally had an issue with it trying to use python2.7 like this [issue](https://github.com/dirkjanm/BloodHound.py/issues/161), but think I resolved it with changing the command to what I have below.

`sudo python3 /usr/local/bin/bloodhound-python -d MARVEL.local -u fcastle -p Password1 -ns 192.168.71.143 -c all`

However, when I run this I now get the following error.

`Traceback (most recent call last):
  File "/usr/local/bin/bloodhound-python", line 5, in <module>
    from bloodhound import main
ModuleNotFoundError: No module named 'bloodhound'`

Thanks for any help, if you need more info let me know!

**Comment by dirkjanm** [comment]
Sounds like your installation is broken, because it can find the script but not the library. To avoid things like this, I recommend running bloodhound.py inside a virtual environment

**Comment by RunRenegade** [comment]
Thanks for the advice, I was actually within a VM.
I have since come back to it and got the program running with no issues. Annoyingly, no idea why it works now but didn't before.
Thanks again.
