### ISSUE TITLE
LDAP Anonymous Bind support

### ISSUE THREAD

**Issue by executionByFork** [dirkjanm/BloodHound.py#178]
I'm not seeing a way to use this tool to query a DC with LDAP anonymous bind enabled. I just came across a CTF box which allows anonymous binding to query AD, and I want to pull bloodhound data. Seems this doesn't support that though, unless I am missing how?

**Comment by dirkjanm** [comment]
hey, this is indeed not supported. Usually CTFs are designed to change things in a certain way so that existing tools don't work. Things like anonymous binds aren't really something you'd see realistically in real environments, so they are out of scope for this project.
