### ISSUE TITLE
I was able to run bloodhound-python the first time but now I get this error every single time

### ISSUE THREAD

**Issue by andypoon-0311** [dirkjanm/BloodHound.py#190]
`Traceback (most recent call last):
  File "/home/andy/.local/bin/bloodhound-python", line 5, in <module>
    from bloodhound import main
  File "/home/andy/.local/lib/python2.7/site-packages/bloodhound/__init__.py", line 27, in <module>
    from bloodhound.ad.domain import AD, ADDC
  File "/home/andy/.local/lib/python2.7/site-packages/bloodhound/ad/domain.py", line 190
    yield from self.search(search_filter, attributes, search_base, generator, use_gc, use_resolver, query_sd, is_retry=True)
             ^
SyntaxError: invalid syntax
`

**Comment by dirkjanm** [comment]
newer versions of bloodhound.py are python3 only, from the error it appears you're trying to run it with python 2

**Comment by andypoon-0311** [comment]
Ah okay I was able to finally run it thank you. Had to run with by specifiying its exact directory. 

`sudo /home/kali/.local/bin/bloodhound-python -d MARVEL.local -u fcastle -p Password -ns 192.168.122.129 -c all`
